heat_template_version: 2015-04-30

description: Deploy a single Windows Server 2016 instance

resources:
  win2k16_instance:
    type: OS::Nova::Server
    properties:
      image: WINDOWS-SERVER-2016-x86_64-20230502
      flavor: g.standard.medium
      networks:
        - network: provider_net_shared_3

outputs:
  win2k16_instance_ip:
    description: IP address of deployed instance
    value: { get_attr: [win2k16_instance, first_address] }